In [99]:
import pandas as pd

In [100]:
covidWorldwide = pd.read_csv('https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv')
covidWorldwide['continent'] = covidWorldwide['continent'].fillna(covidWorldwide['location'])

In [108]:
covidWorldwideAus = covidWorldwide[(covidWorldwide['date'] == '2020-07-24') & (covidWorldwide['location'] == 'Australia')]

iso_code                            object
continent                           object
location                            object
date                                object
total_cases                        float64
new_cases                          float64
total_deaths                       float64
new_deaths                         float64
total_cases_per_million            float64
new_cases_per_million              float64
total_deaths_per_million           float64
new_deaths_per_million             float64
new_tests                          float64
total_tests                        float64
total_tests_per_thousand           float64
new_tests_per_thousand             float64
new_tests_smoothed                 float64
new_tests_smoothed_per_thousand    float64
tests_units                         object
stringency_index                   float64
population                         float64
population_density                 float64
median_age                         float64
aged_65_older                      float64
aged_70_older                      float64
gdp_per_capita                     float64
extreme_poverty                    float64
cardiovasc_death_rate              float64
diabetes_prevalence                float64
female_smokers                     float64
male_smokers                       float64
handwashing_facilities             float64
hospital_beds_per_thousand         float64
life_expectancy                    float64
dtype: object

In [109]:
covidWorldwideAus['date'] = pd.to_datetime(covidWorldwideAus['date'])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [111]:
covidWorldwideAus.dtypes

iso_code                                   object
continent                                  object
location                                   object
date                               datetime64[ns]
total_cases                               float64
new_cases                                 float64
total_deaths                              float64
new_deaths                                float64
total_cases_per_million                   float64
new_cases_per_million                     float64
total_deaths_per_million                  float64
new_deaths_per_million                    float64
new_tests                                 float64
total_tests                               float64
total_tests_per_thousand                  float64
new_tests_per_thousand                    float64
new_tests_smoothed                        float64
new_tests_smoothed_per_thousand           float64
tests_units                                object
stringency_index                          float64
population                                float64
population_density                        float64
median_age                                float64
aged_65_older                             float64
aged_70_older                             float64
gdp_per_capita                            float64
extreme_poverty                           float64
cardiovasc_death_rate                     float64
diabetes_prevalence                       float64
female_smokers                            float64
male_smokers                              float64
handwashing_facilities                    float64
hospital_beds_per_thousand                float64
life_expectancy                           float64
dtype: object

In [103]:
confirmed = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')
death = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')
Recovered = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv')

In [104]:
del confirmed['Lat']
del confirmed['Long']

In [107]:
confirmed = confirmed.rename(columns = {'Province/State':'State','Country/Region':'Country'})
confirmedtransform =confirmed.melt(id_vars = ['State','Country'])
confirmedtransform = confirmedtransform.rename(columns = {'variable':'Date','value':'Cases'})
confirmedtransform['Date'] = pd.to_datetime(confirmedtransform['Date'])
confirmedtransformAus = confirmedtransform[(confirmedtransform['Date'] == '2020-07-24') & (confirmedtransform['Country'] == 'Australia')]
confirmedtransformAus.dtypes

State              object
Country            object
Date       datetime64[ns]
Cases               int64
dtype: object

In [113]:
mergecases = pd.merge(confirmedtransformAus,covidWorldwideAus,how = 'outer',left_on = ['Country','Date'],right_on = ['location','date'])
mergecases

,State,Country,Date,Cases,iso_code,continent,location,date,total_cases,new_cases,...,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy
0,Australian Capital Territory,Australia,2020-07-24,113,AUS,Oceania,Australia,2020-07-24,13306.0,410.0,...,10.129,44648.71,0.5,107.791,5.07,13.0,16.5,NaN,3.84,83.44
1,New South Wales,Australia,2020-07-24,3654,AUS,Oceania,Australia,2020-07-24,13306.0,410.0,...,10.129,44648.71,0.5,107.791,5.07,13.0,16.5,NaN,3.84,83.44
2,Northern Territory,Australia,2020-07-24,31,AUS,Oceania,Australia,2020-07-24,13306.0,410.0,...,10.129,44648.71,0.5,107.791,5.07,13.0,16.5,NaN,3.84,83.44
3,Queensland,Australia,2020-07-24,1076,AUS,Oceania,Australia,2020-07-24,13306.0,410.0,...,10.129,44648.71,0.5,107.791,5.07,13.0,16.5,NaN,3.84,83.44
4,South Australia,Australia,2020-07-24,447,AUS,Oceania,Australia,2020-07-24,13306.0,410.0,...,10.129,44648.71,0.5,107.791,5.07,13.0,16.5,NaN,3.84,83.44
5,Tasmania,Australia,2020-07-24,229,AUS,Oceania,Australia,2020-07-24,13306.0,410.0,...,10.129,44648.71,0.5,107.791,5.07,13.0,16.5,NaN,3.84,83.44
6,Victoria,Australia,2020-07-24,7744,AUS,Oceania,Australia,2020-07-24,13306.0,410.0,...,10.129,44648.71,0.5,107.791,5.07,13.0,16.5,NaN,3.84,83.44
7,Western Australia,Australia,2020-07-24,656,AUS,Oceania,Australia,2020-07-24,13306.0,410.0,...,10.129,44648.71,0.5,107.791,5.07,13.0,16.5,NaN,3.84,83.44